const jwt = require("../services/jwtServices");
const bcryptjs = require("bcryptjs");
const { User, validate, validatePassword } = require("../models/userModel");
const authMiddleware = require("../middleware/authMiddleware");
var nodemailer = require("nodemailer");
const dotenv = require("dotenv");
dotenv.config();

async function postUser(req, res) {
  const params = validate(req.body);
  //console.log(params.value); value is generated by validate method.
  const user = new User(params.value);

  try {
    if (params.error)
      throw {
        msg: `${params.error}`,
      };
    //require email and password
    if (!params.value.email)
      throw {
        msg: "Error: email can not be null",
      };
    if (!params.value.password)
      throw {
        msg: "Error: password can not be null",
      };

    //Avoid duplicated emails
    const emailExists = await User.findOne({
      email: params.value.email,
    });
    if (emailExists)
      throw {
        msg: "Email already exists",
      };

    // encrypting password
    const salt = bcryptjs.genSaltSync(10);
    user.password = await bcryptjs.hash(params.value.password, salt);

    user.save();
    res.status(201).send({
      user: user,
    });
  } catch (error) {
    res.status(500).send(error);
  }
}

async function login(req, res) {
  const { email, password } = req.body;
  try {
    User.findOne(
      {
        email: email,
      },
      async (err, userData) => {
        if (err) {
          res.status(500).send({
            msg: "Server status error",
          });
        } else {
          if (!userData) {
            res.status(400).send({
              msg: "Error: email doesn't exists",
            });
          } else {
            //Check if password match the encrypted pwr
            const passwordCorrect = await bcryptjs.compare(
              password,
              userData.password
            );
            if (!passwordCorrect) {
              res.status(403).send({
                msg: "Error incorrect password",
              });
            } else {
              //Create token with 24h of validation establish in createToken func. in jwtServices.js
              const token = await jwt.createToken(userData, "24h");
              res.status(200).send({
                token: token,
              });
            }
          }
        }
      }
    );
  } catch (error) {
    req.status(500).send(error);
  }
}

async function getUser(req, res) {
  const user_token = await authMiddleware.getUser(req, res);
  console.log(user_token);

  try {
    const user = await User.findById(user_token.id);
    console.log(user);

    if (!user) {
      res.status(404).send({
        msg: "Error: user doesn't exist",
      });
    } else if (user._id != user_token.id) {
      res.status(403).send({
        msg: "Forbidden -- Access to this resource on the server is denied!",
      });
    } else {
      //remove password for security reasons
      user.password = null;
      res.status(200).send({
        user: user,
      });
    }
  } catch (error) {
    res.status(500).send(error);
  }
}

async function putUser(req, res) {
  const params = req.body;
  const user_token = await authMiddleware.getUser(req, res);

  try {
    //get the user
    User.findById(user_token.id, async (err, userData) => {
      if (err) {
        res.status(500).send({
          msg: "Server status error",
        });
      } else {
        //if there is no data or it is not found throw error
        if (!userData) {
          res.status(404).send({
            msg: "Error: User not found",
          });
        } else if (user_token.id !== userData._id.valueOf()) {
          res.status(403).send({
            msg: "Error: unauthorized request",
          });
        } else {
          userData.name = params.name;
          userData.lastName = params.lastName;
          userData.email = params.email;
          userData.gender = params.gender;
          userData.avatar = params.avatar;
          userData.birthday = params.birthday;
          const checkOldPassword = await bcryptjs.compare(
            params.oldPassword,
            userData.password
          );
          const salt = bcryptjs.genSaltSync(10);

          if (params.password) {
            if (checkOldPassword) {
              userData.password = await bcryptjs.hash(params.password, salt);

              User.findByIdAndUpdate(user_token.id, userData, (err, result) => {
                if (userData.error !== undefined) {
                  res.status(403).send({
                    msg: `Error: Validation error`,
                  });
                } else if (err) {
                  res.status(500).send({
                    msg: "Server status error",
                  });
                } else if (!result) {
                  res.status(404).send({
                    msg: "Error: user doesn't exists",
                  });
                } else {
                  res.status(201).send({
                    msg: "User updated successfully",
                  });
                }
              });
            } else if (!checkOldPassword) {
              res.send({ msg: "Error: Old password did not match" });
            }
          }
        }
      }
    });
  } catch (error) {
    console.error(error);
  }
}

async function deleteUser(req, res) {
  const user_token = await authMiddleware.getUser(req, res);
  console.log(user_token);

  try {
    User.findById(user_token.id, (err, userData) => {
      if (err) {
        res.status(500).send({
          msg: "Server status error",
        });
      } else if (user_token.id !== userData.id.valueOf()) {
        res.status(403).send({
          msg: "Error: unauthorized request",
        });
      }
      User.findByIdAndDelete(user_token.id, (err, result) => {
        if (err) {
          res.status(500).send({
            msg: "Server status error",
          });
        } else if (!result) {
          res.status(404).send({
            msg: "Error: User doesn't exist",
          });
        }
        res.status(200).send({
          msg: "User deleted successfully",
        });
      });
    });
  } catch (error) {
    res.status(500).send({
      msg: "Server status error",
    });
  }
}

async function sendEmail(req, res) {
  const { email } = req.body;

  try {
    const user = await User.findOne({ email });

    if (!user) {
      res.status(400).send({
        msg: "User with this email doesn't exists",
      });
    } else {
      const token = jwt.createToken(user, "30m");
      let transporter = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 465,
        secure: true,
        auth: {
          user: process.env.GOOGLE_APP_EMAIL,
          pass: process.env.GOOGLE_APP_PW,
        },
      });

      const url = "https://melodystream.herokuapp.com";
      const data = {
        from: "noreply@melody.com",
        to: email,
        subject: "Reset Account Password Link",
        html: `
        <h3>You requested to reset your password.</h3>
        <h3>Please click the link bellow to reset your password</h3>
    <p>${url}/resetpassword/${token}</p>`,
      };

      await User.updateOne({ resetLink: token }, (err) => {
        if (err) {
          return res.status(400).send({ error: "reset password link error" });
        } else {
          transporter.sendMail(data, function (error) {
            if (error) {
              return res.status(400).send({ error: error.message });
            }
            return res.status(200).send({
              message: "Email has been sent, please follow the instructions",
            });
          });
        }
      }).clone();
    }
  } catch (error) {
    return res.status(400).send({ error: error.message });
  }
}

async function resetPassword(req, res) {
  const user_token = await authMiddleware.recoveryPasswordToken(req, res);
  console.log(user_token);
  //!Check invalid token
  if (!user_token) {
    return res.status(400).send("Invalid link or expired");
  } else return res.status(200).send(req.user_token);
}

async function changePassword(req, res) {
  const user_token = await authMiddleware.getUser(req, res);
  const params = validatePassword(req.body);

  try {
    if (params.error) {
      res.status(400).send({ msg: `${params.error}` });
    } else {
      User.findById(user_token.id, async (err, userData) => {
        if (err) {
          res.status(500).send({
            msg: "Server status error",
          });
        } else {
          if (!userData) {
            res.status(404).send({
              msg: "Error: User not found",
            });
          } else if (user_token.id !== userData._id.valueOf()) {
            res.status(403).send({
              msg: "Error: unauthorized request",
            });
          } else {
            const salt = bcryptjs.genSaltSync(10);
            userData.password = await bcryptjs.hash(
              params.value.password,
              salt
            );
          }
        }
        User.findByIdAndUpdate(user_token.id, userData, (err, result) => {
          if (err) {
            res.status(500).send({
              msg: "Server status error",
            });
          } else if (!result) {
            res.status(404).send({
              msg: "Error: user doesn't exists",
            });
          } else {
            res.status(201).send({
              user: userData,
            });
          }
        });
      });
    }
  } catch (error) {
    console.error(error);
  }
}

module.exports = {
  postUser,
  login,
  getUser,
  putUser,
  deleteUser,
  sendEmail,
  changePassword,
  resetPassword,
};
